apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30429
    name: jenkins
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    git_version: "1.0"
    version: "1.0"
    name: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: "1.0"
        git_version: "1.0"
    spec:
      containers:
      - name: jenkins
        image: jaganthoutam/jenkins-master-docker:latest
        imagePullPolicy: Always
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: '-Djenkins.install.runSetupWizard=false'
        volumeMounts:
        - name: jenkins-storage
          mountPath: '/var/jenkins_home'
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
#For AWS EFS Mount
#       - name: jenkins-storage
#         nfs:
#           server: 'EFSID.amazonaws.com'
#           path: '/'
# For hostpath WARNING Not for Production
      - name: jenkins-storage
        hostPath:
          path: '/tmp/jenkins'
